# Generated by Django 5.0.3 on 2024-04-20 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('birthday', models.TimeField(null=True)),
                ('country', models.CharField(max_length=25, null=True)),
                ('city', models.CharField(max_length=25, null=True)),
                ('state', models.CharField(max_length=25, null=True)),
                ('avatar_url', models.TextField(null=True)),
                ('is_actived', models.IntegerField(null=True, verbose_name=django.core.validators.MaxValueValidator(1))),
                ('is_verified', models.IntegerField(null=True, verbose_name=django.core.validators.MaxValueValidator(1))),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users_baned',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_permaban', models.BooleanField()),
                ('ban_expired_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'user_bans',
                'managed': False,
            },
        ),
    ]
